name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        os: [ubuntu-20.04]

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create and start a virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        export SDK_PATH=/opt/gc/poplar_sdk-ubuntu_20_04-3.2*
        pip install ${SDK_PATH}/poptorch-*.whl
        pip install .[testing]
        pip install memory-profiler
    - name: Test with Pytest
      run: |
        source venv/bin/activate
        export SDK_PATH=/opt/gc/poplar_sdk-ubuntu_20_04-3.2*
        . ${SDK_PATH}/poplar-ubuntu_20_04*/enable.sh
        . ${SDK_PATH}/popart-ubuntu_20_04*/enable.sh
        export POPTORCH_WAIT_FOR_IPU=1
        memprof run --interval 1 --include-children --multiprocess \
          pytest tests/ -v -n 16 --ignore=tests/pipelines/ --ignore=tests/test_examples_match_transformers.py
        memprof plot -o memory_profile.png
        pytest tests/test_examples_match_transformers.py -v
    - name: Upload memory profile
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: memory_profile
        path: memory_profile.png
    - name: Upload PopTorch error log if present
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: poptorch_error
        path: poptorch_error.log
        if-no-files-found: ignore
