name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        os: [ubuntu-20.04]

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create and start a virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        export SDK_PATH=/opt/gc/poplar_sdk-ubuntu_20_04-3.1*
        pip install ${SDK_PATH}/poptorch-*.whl
        pip install .[testing]
    - name: Test with Pytest
      run: |
        source venv/bin/activate
        export SDK_PATH=/opt/gc/poplar_sdk-ubuntu_20_04-3.1*
        . ${SDK_PATH}/poplar-ubuntu_20_04*/enable.sh
        . ${SDK_PATH}/popart-ubuntu_20_04*/enable.sh
        export POPTORCH_WAIT_FOR_IPU=1
        pytest tests/ -n 16 --ignore=tests/pipelines/ --ignore=tests/test_examples_match_transformers.py
        pytest tests/test_examples_match_transformers.py
